### ISSUE TITLE
productById returns null fields

### ISSUE THREAD

**Issue by shawub** [0xR/graphql-transform-federation#4]
Hi, great work!
I can run the demo and findProduct works ok but productById returns null for price, weight.
Is this intended behaviour. Is it possible to make this work also?
Thanks

**Comment by shawub** [comment]
A follow up question. I have built a demo app which attempts to extend a remote schema. When I call delegateToSchema I see an error "Error: fetcher is not a function".  Any ideas on this

**Comment by VijayManchi** [comment]
@shawub, can you please explain how you were able to resolve the null values issue for price and weight?
